export const reducerCases = {
    SET_USER_INFO: "SET_USER_INFO",
    CHANGE_CURRENT_CHAT_USER: "CHANGE_CURRENT_CHAT_USER",
    SET_MESSAGES: "SET_MESSAGES",
    SET_LOCATION: "SET_LOCATION",
    ADD_MESSAGE: "ADD_MESSAGE",
    SET_SOCKET: "SET_SOCKET",
    SOCKET_EVENT: "SOCKET_EVENT",
    ADD_OTHERS_MESSAGE:"ADD_OTHER_MESSAGE",
    SET_OTHERS_MESSAGE:"SET_OTHERS_MESSAGE",
    SET_CHAT_CONTAINER_REF:"SET_CHAT_CONTAINER_REF",
}